/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BakerySettings {
  'heroCtaText' : string,
  'aboutTitle' : string,
  'email' : string,
  'aboutImageId' : [] | [string],
  'aboutBody' : string,
  'address' : string,
  'openingHours' : Array<OpeningHour>,
  'phone' : string,
  'heroHeadline' : string,
  'heroSubheading' : string,
}
export type ExternalBlob = Uint8Array;
export interface MenuItem {
  'id' : string,
  'name' : string,
  'createdAt' : Time,
  'isAvailable' : boolean,
  'description' : string,
  'updatedAt' : Time,
  'category' : string,
  'imageId' : [] | [ExternalBlob],
  'price' : string,
}
export interface OpeningHour { 'day' : string, 'hours' : string }
export type Time = bigint;
export interface OrderItem {
  'menuItemId' : string,
  'name' : string,
  'quantity' : bigint,
  'price' : string,
}
export interface CustomerOrder {
  'id' : string,
  'customerName' : string,
  'customerPhone' : string,
  'customerEmail' : string,
  'items' : Array<OrderItem>,
  'totalPrice' : string,
  'status' : string,
  'notes' : string,
  'createdAt' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createMenuItem' : ActorMethod<[MenuItem], string>,
  'deleteMenuItem' : ActorMethod<[string], undefined>,
  'getAllMenuItems' : ActorMethod<[], Array<MenuItem>>,
  'getAvailableMenuItems' : ActorMethod<[], Array<MenuItem>>,
  'getBakerySettings' : ActorMethod<[], BakerySettings>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMenuItem' : ActorMethod<[string], MenuItem>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<[CustomerOrder], string>,
  'getAllOrders' : ActorMethod<[], Array<CustomerOrder>>,
  'updateOrderStatus' : ActorMethod<[string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateBakerySettings' : ActorMethod<[BakerySettings], undefined>,
  'updateMenuItem' : ActorMethod<[string, MenuItem], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];