/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const MenuItem = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'isAvailable' : IDL.Bool,
  'description' : IDL.Text,
  'updatedAt' : Time,
  'category' : IDL.Text,
  'imageId' : IDL.Opt(ExternalBlob),
  'price' : IDL.Text,
});
export const OpeningHour = IDL.Record({ 'day' : IDL.Text, 'hours' : IDL.Text });
export const BakerySettings = IDL.Record({
  'heroCtaText' : IDL.Text,
  'aboutTitle' : IDL.Text,
  'email' : IDL.Text,
  'aboutImageId' : IDL.Opt(IDL.Text),
  'aboutBody' : IDL.Text,
  'address' : IDL.Text,
  'openingHours' : IDL.Vec(OpeningHour),
  'phone' : IDL.Text,
  'heroHeadline' : IDL.Text,
  'heroSubheading' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const OrderItem = IDL.Record({
  'menuItemId' : IDL.Text,
  'name' : IDL.Text,
  'quantity' : IDL.Nat,
  'price' : IDL.Text,
});
export const CustomerOrder = IDL.Record({
  'id' : IDL.Text,
  'customerName' : IDL.Text,
  'customerPhone' : IDL.Text,
  'customerEmail' : IDL.Text,
  'items' : IDL.Vec(OrderItem),
  'totalPrice' : IDL.Text,
  'status' : IDL.Text,
  'notes' : IDL.Text,
  'createdAt' : IDL.Int,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createMenuItem' : IDL.Func([MenuItem], [IDL.Text], []),
  'deleteMenuItem' : IDL.Func([IDL.Text], [], []),
  'getAllMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'getAvailableMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'getBakerySettings' : IDL.Func([], [BakerySettings], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMenuItem' : IDL.Func([IDL.Text], [MenuItem], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func([CustomerOrder], [IDL.Text], []),
  'getAllOrders' : IDL.Func([], [IDL.Vec(CustomerOrder)], []),
  'updateOrderStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateBakerySettings' : IDL.Func([BakerySettings], [], []),
  'updateMenuItem' : IDL.Func([IDL.Text, MenuItem], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const MenuItem = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'isAvailable' : IDL.Bool,
    'description' : IDL.Text,
    'updatedAt' : Time,
    'category' : IDL.Text,
    'imageId' : IDL.Opt(ExternalBlob),
    'price' : IDL.Text,
  });
  const OpeningHour = IDL.Record({ 'day' : IDL.Text, 'hours' : IDL.Text });
  const BakerySettings = IDL.Record({
    'heroCtaText' : IDL.Text,
    'aboutTitle' : IDL.Text,
    'email' : IDL.Text,
    'aboutImageId' : IDL.Opt(IDL.Text),
    'aboutBody' : IDL.Text,
    'address' : IDL.Text,
    'openingHours' : IDL.Vec(OpeningHour),
    'phone' : IDL.Text,
    'heroHeadline' : IDL.Text,
    'heroSubheading' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const OrderItem = IDL.Record({
    'menuItemId' : IDL.Text,
    'name' : IDL.Text,
    'quantity' : IDL.Nat,
    'price' : IDL.Text,
  });
  const CustomerOrder = IDL.Record({
    'id' : IDL.Text,
    'customerName' : IDL.Text,
    'customerPhone' : IDL.Text,
    'customerEmail' : IDL.Text,
    'items' : IDL.Vec(OrderItem),
    'totalPrice' : IDL.Text,
    'status' : IDL.Text,
    'notes' : IDL.Text,
    'createdAt' : IDL.Int,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createMenuItem' : IDL.Func([MenuItem], [IDL.Text], []),
    'deleteMenuItem' : IDL.Func([IDL.Text], [], []),
    'getAllMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'getAvailableMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'getBakerySettings' : IDL.Func([], [BakerySettings], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMenuItem' : IDL.Func([IDL.Text], [MenuItem], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func([CustomerOrder], [IDL.Text], []),
    'getAllOrders' : IDL.Func([], [IDL.Vec(CustomerOrder)], []),
    'updateOrderStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateBakerySettings' : IDL.Func([BakerySettings], [], []),
    'updateMenuItem' : IDL.Func([IDL.Text, MenuItem], [], []),
  });
};

export const init = ({ IDL }) => { return []; };
